"""add national search vectors

Revision ID: 04582d2f4d34
Revises: f39f6ee7f2b4
Create Date: 2026-07-15 11:15:57.172705
"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "04582d2f4d34"
down_revision: Union[str, None] = "f39f6ee7f2b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS unaccent")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sites", sa.Column("search_vector", postgresql.TSVECTOR(), nullable=True), schema="atlas")
    op.create_index(
        "ix_sites_search_vector_gin", "sites", ["search_vector"], unique=False, schema="atlas", postgresql_using="gin"
    )
    op.add_column("import_features", sa.Column("search_vector", postgresql.TSVECTOR(), nullable=True), schema="staging")
    op.create_index(
        "ix_import_features_name_ar_trgm",
        "import_features",
        ["name_ar"],
        unique=False,
        schema="staging",
        postgresql_using="gin",
        postgresql_ops={"name_ar": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_import_features_search_vector_gin",
        "import_features",
        ["search_vector"],
        unique=False,
        schema="staging",
        postgresql_using="gin",
    )
    op.execute("""
    CREATE OR REPLACE FUNCTION atlas.update_site_search_vector() RETURNS trigger AS $$
    BEGIN
      NEW.search_vector := to_tsvector('simple', unaccent(coalesce(NEW.name_ar,'') || ' ' || coalesce(NEW.name_en,'') || ' ' || coalesce(NEW.description,'')));
      RETURN NEW;
    END $$ LANGUAGE plpgsql;
    CREATE TRIGGER trg_sites_search_vector BEFORE INSERT OR UPDATE OF name_ar, name_en, description ON atlas.sites FOR EACH ROW EXECUTE FUNCTION atlas.update_site_search_vector();
    CREATE OR REPLACE FUNCTION staging.update_feature_search_vector() RETURNS trigger AS $$
    BEGIN
      NEW.search_vector := to_tsvector('simple', unaccent(coalesce(NEW.name_ar,'') || ' ' || coalesce(NEW.properties->>'name_en','') || ' ' || coalesce(NEW.properties->>'description_text','') || ' ' || coalesce(NEW.properties->>'folder_name','')));
      RETURN NEW;
    END $$ LANGUAGE plpgsql;
    CREATE TRIGGER trg_import_features_search_vector BEFORE INSERT OR UPDATE OF name_ar, properties ON staging.import_features FOR EACH ROW EXECUTE FUNCTION staging.update_feature_search_vector();
    UPDATE atlas.sites SET search_vector = to_tsvector('simple', unaccent(coalesce(name_ar,'') || ' ' || coalesce(name_en,'') || ' ' || coalesce(description,'')));
    UPDATE staging.import_features SET search_vector = to_tsvector('simple', unaccent(coalesce(name_ar,'') || ' ' || coalesce(properties->>'name_en','') || ' ' || coalesce(properties->>'description_text','') || ' ' || coalesce(properties->>'folder_name','')));
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute(
        "DROP TRIGGER IF EXISTS trg_import_features_search_vector ON staging.import_features; DROP FUNCTION IF EXISTS staging.update_feature_search_vector(); DROP TRIGGER IF EXISTS trg_sites_search_vector ON atlas.sites; DROP FUNCTION IF EXISTS atlas.update_site_search_vector();"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_import_features_search_vector_gin", table_name="import_features", schema="staging", postgresql_using="gin"
    )
    op.drop_index(
        "ix_import_features_name_ar_trgm",
        table_name="import_features",
        schema="staging",
        postgresql_using="gin",
        postgresql_ops={"name_ar": "gin_trgm_ops"},
    )
    op.drop_column("import_features", "search_vector", schema="staging")
    op.drop_index("ix_sites_search_vector_gin", table_name="sites", schema="atlas", postgresql_using="gin")
    op.drop_column("sites", "search_vector", schema="atlas")
    # ### end Alembic commands ###
