"""add national asset registry engine

Revision ID: 2f61cbe32a4b
Revises: be162a170240
Create Date: 2026-07-14 17:53:56.525581
"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "2f61cbe32a4b"
down_revision: Union[str, None] = "be162a170240"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "site_attributes",
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("attribute_group", sa.String(length=120), nullable=False),
        sa.Column("attribute_key", sa.String(length=160), nullable=False),
        sa.Column("label_ar", sa.String(length=255), nullable=False),
        sa.Column("label_en", sa.String(length=255), nullable=True),
        sa.Column("value_text", sa.Text(), nullable=True),
        sa.Column("value_number", sa.Numeric(), nullable=True),
        sa.Column("value_boolean", sa.Boolean(), nullable=True),
        sa.Column("value_date", sa.Date(), nullable=True),
        sa.Column("value_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("unit", sa.String(length=80), nullable=True),
        sa.Column("source_reference", sa.Text(), nullable=True),
        sa.Column("verification_status", sa.String(length=40), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["site_id"], ["atlas.sites.id"], name=op.f("fk_site_attributes_site_id_sites"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_site_attributes")),
        sa.UniqueConstraint("site_id", "attribute_group", "attribute_key", name="uq_site_attribute_key"),
        schema="atlas",
    )
    op.create_index(op.f("ix_site_attributes_site_id"), "site_attributes", ["site_id"], unique=False, schema="atlas")
    op.create_index(
        op.f("ix_site_attributes_verification_status"),
        "site_attributes",
        ["verification_status"],
        unique=False,
        schema="atlas",
    )
    op.create_table(
        "site_documents",
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("document_type", sa.String(length=100), nullable=False),
        sa.Column("title_ar", sa.String(length=500), nullable=False),
        sa.Column("title_en", sa.String(length=500), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("file_name", sa.String(length=500), nullable=False),
        sa.Column("storage_path", sa.Text(), nullable=True),
        sa.Column("original_url", sa.Text(), nullable=True),
        sa.Column("mime_type", sa.String(length=150), nullable=True),
        sa.Column("file_size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("document_date", sa.Date(), nullable=True),
        sa.Column("issuing_organization", sa.String(length=500), nullable=True),
        sa.Column("rights_status", sa.String(length=80), nullable=False),
        sa.Column("verification_status", sa.String(length=40), nullable=False),
        sa.Column("publication_status", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["site_id"], ["atlas.sites.id"], name=op.f("fk_site_documents_site_id_sites"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_site_documents")),
        schema="atlas",
    )
    op.create_index(
        op.f("ix_site_documents_document_type"), "site_documents", ["document_type"], unique=False, schema="atlas"
    )
    op.create_index(
        op.f("ix_site_documents_publication_status"),
        "site_documents",
        ["publication_status"],
        unique=False,
        schema="atlas",
    )
    op.create_index(op.f("ix_site_documents_site_id"), "site_documents", ["site_id"], unique=False, schema="atlas")
    op.create_index(
        "ix_site_documents_title_ar_trgm",
        "site_documents",
        ["title_ar"],
        unique=False,
        schema="atlas",
        postgresql_using="gin",
        postgresql_ops={"title_ar": "gin_trgm_ops"},
    )
    op.create_index(
        op.f("ix_site_documents_verification_status"),
        "site_documents",
        ["verification_status"],
        unique=False,
        schema="atlas",
    )
    op.create_table(
        "site_identifiers",
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("identifier_type", sa.String(length=100), nullable=False),
        sa.Column("identifier_value", sa.String(length=500), nullable=False),
        sa.Column("issuing_authority", sa.String(length=500), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["site_id"], ["atlas.sites.id"], name=op.f("fk_site_identifiers_site_id_sites"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_site_identifiers")),
        sa.UniqueConstraint("identifier_type", "identifier_value", name="uq_site_identifier_value"),
        schema="atlas",
    )
    op.create_index(
        op.f("ix_site_identifiers_identifier_value"),
        "site_identifiers",
        ["identifier_value"],
        unique=False,
        schema="atlas",
    )
    op.create_index(op.f("ix_site_identifiers_site_id"), "site_identifiers", ["site_id"], unique=False, schema="atlas")
    op.create_table(
        "site_profiles",
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("short_description_ar", sa.Text(), nullable=True),
        sa.Column("short_description_en", sa.Text(), nullable=True),
        sa.Column("historical_period", sa.Text(), nullable=True),
        sa.Column("tourism_significance", sa.Text(), nullable=True),
        sa.Column("visitor_information", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("accessibility_information", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("opening_hours", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("contact_information", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("official_website", sa.Text(), nullable=True),
        sa.Column("public_notes", sa.Text(), nullable=True),
        sa.Column("internal_notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["site_id"], ["atlas.sites.id"], name=op.f("fk_site_profiles_site_id_sites"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_site_profiles")),
        schema="atlas",
    )
    op.create_index(op.f("ix_site_profiles_site_id"), "site_profiles", ["site_id"], unique=True, schema="atlas")
    op.create_table(
        "site_quality_snapshots",
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("overall_score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("score_breakdown", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("critical_issues", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("warnings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("calculated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("calculated_by", sa.String(length=120), nullable=False),
        sa.Column("source_version", sa.String(length=80), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["site_id"], ["atlas.sites.id"], name=op.f("fk_site_quality_snapshots_site_id_sites"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_site_quality_snapshots")),
        schema="atlas",
    )
    op.create_index(
        op.f("ix_site_quality_snapshots_site_id"), "site_quality_snapshots", ["site_id"], unique=False, schema="atlas"
    )
    op.create_table(
        "site_relationships",
        sa.Column("source_site_id", sa.Uuid(), nullable=False),
        sa.Column("target_site_id", sa.Uuid(), nullable=False),
        sa.Column("relationship_type", sa.String(length=80), nullable=False),
        sa.Column("distance_meters", sa.Numeric(), nullable=True),
        sa.Column("relationship_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("verification_status", sa.String(length=40), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "source_site_id <> target_site_id", name=op.f("ck_site_relationships_site_relationship_not_self")
        ),
        sa.ForeignKeyConstraint(
            ["source_site_id"],
            ["atlas.sites.id"],
            name=op.f("fk_site_relationships_source_site_id_sites"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_site_id"],
            ["atlas.sites.id"],
            name=op.f("fk_site_relationships_target_site_id_sites"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_site_relationships")),
        sa.UniqueConstraint("source_site_id", "target_site_id", "relationship_type", name="uq_site_relationship"),
        schema="atlas",
    )
    op.create_index(
        op.f("ix_site_relationships_relationship_type"),
        "site_relationships",
        ["relationship_type"],
        unique=False,
        schema="atlas",
    )
    op.create_index(
        op.f("ix_site_relationships_source_site_id"),
        "site_relationships",
        ["source_site_id"],
        unique=False,
        schema="atlas",
    )
    op.create_index(
        op.f("ix_site_relationships_target_site_id"),
        "site_relationships",
        ["target_site_id"],
        unique=False,
        schema="atlas",
    )
    op.create_index(
        op.f("ix_site_relationships_verification_status"),
        "site_relationships",
        ["verification_status"],
        unique=False,
        schema="atlas",
    )
    op.create_table(
        "site_versions",
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("change_summary", sa.Text(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["site_id"], ["atlas.sites.id"], name=op.f("fk_site_versions_site_id_sites"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_site_versions")),
        sa.UniqueConstraint("site_id", "version_number", name="uq_site_version"),
        schema="atlas",
    )
    op.create_index(op.f("ix_site_versions_site_id"), "site_versions", ["site_id"], unique=False, schema="atlas")
    op.add_column("media_assets", sa.Column("caption_ar", sa.Text(), nullable=True), schema="atlas")
    op.add_column("media_assets", sa.Column("caption_en", sa.Text(), nullable=True), schema="atlas")
    op.add_column("media_assets", sa.Column("alt_text_ar", sa.Text(), nullable=True), schema="atlas")
    op.add_column("media_assets", sa.Column("alt_text_en", sa.Text(), nullable=True), schema="atlas")
    op.add_column("media_assets", sa.Column("width", sa.Integer(), nullable=True), schema="atlas")
    op.add_column("media_assets", sa.Column("height", sa.Integer(), nullable=True), schema="atlas")
    op.add_column("media_assets", sa.Column("file_size_bytes", sa.BigInteger(), nullable=True), schema="atlas")
    op.add_column("media_assets", sa.Column("sha256", sa.String(length=64), nullable=True), schema="atlas")
    op.add_column("media_assets", sa.Column("display_order", sa.Integer(), nullable=False), schema="atlas")
    op.add_column(
        "media_assets", sa.Column("verification_status", sa.String(length=40), nullable=False), schema="atlas"
    )
    op.add_column("media_assets", sa.Column("publication_status", sa.String(length=40), nullable=False), schema="atlas")
    op.create_index(
        op.f("ix_media_assets_publication_status"), "media_assets", ["publication_status"], unique=False, schema="atlas"
    )
    op.create_index(
        op.f("ix_media_assets_verification_status"),
        "media_assets",
        ["verification_status"],
        unique=False,
        schema="atlas",
    )
    op.add_column("sites", sa.Column("slug", sa.String(length=600), nullable=True), schema="atlas")
    op.add_column(
        "sites",
        sa.Column("profile_completeness_score", sa.Numeric(precision=5, scale=2), nullable=True),
        schema="atlas",
    )
    op.add_column("sites", sa.Column("primary_geometry_id", sa.Uuid(), nullable=True), schema="atlas")
    op.add_column("sites", sa.Column("primary_media_id", sa.Uuid(), nullable=True), schema="atlas")
    op.add_column("sites", sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True), schema="atlas")
    op.add_column("sites", sa.Column("approved_by", sa.Uuid(), nullable=True), schema="atlas")
    op.create_unique_constraint(op.f("uq_sites_slug"), "sites", ["slug"], schema="atlas")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_sites_slug"), "sites", schema="atlas", type_="unique")
    op.drop_column("sites", "approved_by", schema="atlas")
    op.drop_column("sites", "approved_at", schema="atlas")
    op.drop_column("sites", "primary_media_id", schema="atlas")
    op.drop_column("sites", "primary_geometry_id", schema="atlas")
    op.drop_column("sites", "profile_completeness_score", schema="atlas")
    op.drop_column("sites", "slug", schema="atlas")
    op.drop_index(op.f("ix_media_assets_verification_status"), table_name="media_assets", schema="atlas")
    op.drop_index(op.f("ix_media_assets_publication_status"), table_name="media_assets", schema="atlas")
    op.drop_column("media_assets", "publication_status", schema="atlas")
    op.drop_column("media_assets", "verification_status", schema="atlas")
    op.drop_column("media_assets", "display_order", schema="atlas")
    op.drop_column("media_assets", "sha256", schema="atlas")
    op.drop_column("media_assets", "file_size_bytes", schema="atlas")
    op.drop_column("media_assets", "height", schema="atlas")
    op.drop_column("media_assets", "width", schema="atlas")
    op.drop_column("media_assets", "alt_text_en", schema="atlas")
    op.drop_column("media_assets", "alt_text_ar", schema="atlas")
    op.drop_column("media_assets", "caption_en", schema="atlas")
    op.drop_column("media_assets", "caption_ar", schema="atlas")
    op.drop_index(op.f("ix_site_versions_site_id"), table_name="site_versions", schema="atlas")
    op.drop_table("site_versions", schema="atlas")
    op.drop_index(op.f("ix_site_relationships_verification_status"), table_name="site_relationships", schema="atlas")
    op.drop_index(op.f("ix_site_relationships_target_site_id"), table_name="site_relationships", schema="atlas")
    op.drop_index(op.f("ix_site_relationships_source_site_id"), table_name="site_relationships", schema="atlas")
    op.drop_index(op.f("ix_site_relationships_relationship_type"), table_name="site_relationships", schema="atlas")
    op.drop_table("site_relationships", schema="atlas")
    op.drop_index(op.f("ix_site_quality_snapshots_site_id"), table_name="site_quality_snapshots", schema="atlas")
    op.drop_table("site_quality_snapshots", schema="atlas")
    op.drop_index(op.f("ix_site_profiles_site_id"), table_name="site_profiles", schema="atlas")
    op.drop_table("site_profiles", schema="atlas")
    op.drop_index(op.f("ix_site_identifiers_site_id"), table_name="site_identifiers", schema="atlas")
    op.drop_index(op.f("ix_site_identifiers_identifier_value"), table_name="site_identifiers", schema="atlas")
    op.drop_table("site_identifiers", schema="atlas")
    op.drop_index(op.f("ix_site_documents_verification_status"), table_name="site_documents", schema="atlas")
    op.drop_index(
        "ix_site_documents_title_ar_trgm",
        table_name="site_documents",
        schema="atlas",
        postgresql_using="gin",
        postgresql_ops={"title_ar": "gin_trgm_ops"},
    )
    op.drop_index(op.f("ix_site_documents_site_id"), table_name="site_documents", schema="atlas")
    op.drop_index(op.f("ix_site_documents_publication_status"), table_name="site_documents", schema="atlas")
    op.drop_index(op.f("ix_site_documents_document_type"), table_name="site_documents", schema="atlas")
    op.drop_table("site_documents", schema="atlas")
    op.drop_index(op.f("ix_site_attributes_verification_status"), table_name="site_attributes", schema="atlas")
    op.drop_index(op.f("ix_site_attributes_site_id"), table_name="site_attributes", schema="atlas")
    op.drop_table("site_attributes", schema="atlas")
    # ### end Alembic commands ###
