"""add staging review and promotion workflow

Revision ID: be162a170240
Revises: c4658a331e6d
Create Date: 2026-07-14 15:12:53.954177
"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "be162a170240"
down_revision: Union[str, None] = "c4658a331e6d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE SEQUENCE IF NOT EXISTS atlas.old_tripoli_national_id_seq START WITH 1 INCREMENT BY 1 NO CYCLE")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feature_reviews",
        sa.Column("import_feature_id", sa.Uuid(), nullable=False),
        sa.Column("review_stage", sa.String(length=30), nullable=False),
        sa.Column("decision", sa.String(length=30), nullable=False),
        sa.Column("reviewer_id", sa.Uuid(), nullable=True),
        sa.Column("reviewer_role", sa.String(length=120), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("proposed_name_ar", sa.String(length=500), nullable=True),
        sa.Column("proposed_category_id", sa.Uuid(), nullable=True),
        sa.Column("proposed_municipality_id", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "decision IN ('pending', 'accepted', 'rejected', 'needs_correction')",
            name=op.f("ck_feature_reviews_feature_reviews_decision"),
        ),
        sa.CheckConstraint(
            "review_stage IN ('technical', 'gis', 'data', 'final')",
            name=op.f("ck_feature_reviews_feature_reviews_stage"),
        ),
        sa.ForeignKeyConstraint(
            ["import_feature_id"],
            ["staging.import_features.id"],
            name=op.f("fk_feature_reviews_import_feature_id_import_features"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_category_id"],
            ["atlas.site_categories.id"],
            name=op.f("fk_feature_reviews_proposed_category_id_site_categories"),
        ),
        sa.ForeignKeyConstraint(
            ["proposed_municipality_id"],
            ["atlas.municipalities.id"],
            name=op.f("fk_feature_reviews_proposed_municipality_id_municipalities"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feature_reviews")),
        sa.UniqueConstraint("import_feature_id", "review_stage", name="uq_feature_reviews_feature_stage"),
        schema="staging",
    )
    op.create_index(
        op.f("ix_feature_reviews_import_feature_id"),
        "feature_reviews",
        ["import_feature_id"],
        unique=False,
        schema="staging",
    )
    op.create_table(
        "promotion_records",
        sa.Column("import_feature_id", sa.Uuid(), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=True),
        sa.Column("promoted_by", sa.Uuid(), nullable=True),
        sa.Column("promoted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending', 'promoted', 'failed', 'cancelled')",
            name=op.f("ck_promotion_records_promotion_records_status"),
        ),
        sa.ForeignKeyConstraint(
            ["import_feature_id"],
            ["staging.import_features.id"],
            name=op.f("fk_promotion_records_import_feature_id_import_features"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["site_id"], ["atlas.sites.id"], name=op.f("fk_promotion_records_site_id_sites")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_promotion_records")),
        sa.UniqueConstraint("import_feature_id", name="uq_promotion_records_import_feature"),
        schema="staging",
    )
    op.add_column(
        "import_features", sa.Column("proposed_national_id", sa.String(length=100), nullable=True), schema="staging"
    )
    op.add_column(
        "import_features", sa.Column("proposed_category_code", sa.String(length=80), nullable=True), schema="staging"
    )
    op.add_column(
        "import_features",
        sa.Column("proposed_municipality_code", sa.String(length=80), nullable=True),
        schema="staging",
    )
    op.add_column(
        "import_features",
        sa.Column("promotion_eligible", sa.Boolean(), server_default="false", nullable=False),
        schema="staging",
    )
    op.add_column(
        "import_features", sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True), schema="staging"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("import_features", "reviewed_at", schema="staging")
    op.drop_column("import_features", "promotion_eligible", schema="staging")
    op.drop_column("import_features", "proposed_municipality_code", schema="staging")
    op.drop_column("import_features", "proposed_category_code", schema="staging")
    op.drop_column("import_features", "proposed_national_id", schema="staging")
    op.drop_table("promotion_records", schema="staging")
    op.drop_index(op.f("ix_feature_reviews_import_feature_id"), table_name="feature_reviews", schema="staging")
    op.drop_table("feature_reviews", schema="staging")
    op.execute("DROP SEQUENCE IF EXISTS atlas.old_tripoli_national_id_seq")
    # ### end Alembic commands ###
