"""expand spatial relationship engine

Revision ID: f39f6ee7f2b4
Revises: 2f61cbe32a4b
Create Date: 2026-07-14 18:32:28.053730
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "f39f6ee7f2b4"
down_revision: Union[str, None] = "2f61cbe32a4b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "site_relationships", sa.Column("target_staging_feature_id", sa.Uuid(), nullable=True), schema="atlas"
    )
    op.add_column(
        "site_relationships",
        sa.Column("relationship_direction", sa.String(length=30), server_default="outbound", nullable=False),
        schema="atlas",
    )
    op.add_column("site_relationships", sa.Column("travel_time_minutes", sa.Numeric(), nullable=True), schema="atlas")
    op.add_column(
        "site_relationships",
        sa.Column("confidence_score", sa.Numeric(precision=5, scale=2), nullable=True),
        schema="atlas",
    )
    op.add_column(
        "site_relationships",
        sa.Column("source_method", sa.String(length=40), server_default="manual", nullable=False),
        schema="atlas",
    )
    op.add_column(
        "site_relationships",
        sa.Column("publication_status", sa.String(length=40), server_default="internal", nullable=False),
        schema="atlas",
    )
    op.add_column("site_relationships", sa.Column("verified_by", sa.Uuid(), nullable=True), schema="atlas")
    op.add_column(
        "site_relationships", sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True), schema="atlas"
    )
    op.alter_column("site_relationships", "target_site_id", existing_type=sa.UUID(), nullable=True, schema="atlas")
    op.create_check_constraint(
        "site_relationship_one_target",
        "site_relationships",
        "(target_site_id IS NOT NULL) <> (target_staging_feature_id IS NOT NULL)",
        schema="atlas",
    )
    op.drop_constraint(op.f("uq_site_relationship"), "site_relationships", schema="atlas", type_="unique")
    op.create_index(
        "ix_site_relationships_metadata_gin",
        "site_relationships",
        ["relationship_metadata"],
        unique=False,
        schema="atlas",
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_site_relationships_publication_status"),
        "site_relationships",
        ["publication_status"],
        unique=False,
        schema="atlas",
    )
    op.create_index(
        op.f("ix_site_relationships_target_staging_feature_id"),
        "site_relationships",
        ["target_staging_feature_id"],
        unique=False,
        schema="atlas",
    )
    op.create_index(
        "uq_site_relationship_registry",
        "site_relationships",
        ["source_site_id", "target_site_id", "relationship_type"],
        unique=True,
        schema="atlas",
        postgresql_where=sa.text("target_site_id IS NOT NULL"),
    )
    op.create_index(
        "uq_site_relationship_staging",
        "site_relationships",
        ["source_site_id", "target_staging_feature_id", "relationship_type"],
        unique=True,
        schema="atlas",
        postgresql_where=sa.text("target_staging_feature_id IS NOT NULL"),
    )
    op.create_foreign_key(
        op.f("fk_site_relationships_target_staging_feature_id_import_features"),
        "site_relationships",
        "import_features",
        ["target_staging_feature_id"],
        ["id"],
        source_schema="atlas",
        referent_schema="staging",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_site_relationships_target_staging_feature_id_import_features"),
        "site_relationships",
        schema="atlas",
        type_="foreignkey",
    )
    op.drop_constraint("site_relationship_one_target", "site_relationships", schema="atlas", type_="check")
    op.drop_index(
        "uq_site_relationship_staging",
        table_name="site_relationships",
        schema="atlas",
        postgresql_where=sa.text("target_staging_feature_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_site_relationship_registry",
        table_name="site_relationships",
        schema="atlas",
        postgresql_where=sa.text("target_site_id IS NOT NULL"),
    )
    op.drop_index(
        op.f("ix_site_relationships_target_staging_feature_id"), table_name="site_relationships", schema="atlas"
    )
    op.drop_index(op.f("ix_site_relationships_publication_status"), table_name="site_relationships", schema="atlas")
    op.drop_index(
        "ix_site_relationships_metadata_gin", table_name="site_relationships", schema="atlas", postgresql_using="gin"
    )
    op.create_unique_constraint(
        op.f("uq_site_relationship"),
        "site_relationships",
        ["source_site_id", "target_site_id", "relationship_type"],
        schema="atlas",
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column("site_relationships", "target_site_id", existing_type=sa.UUID(), nullable=False, schema="atlas")
    op.drop_column("site_relationships", "verified_at", schema="atlas")
    op.drop_column("site_relationships", "verified_by", schema="atlas")
    op.drop_column("site_relationships", "publication_status", schema="atlas")
    op.drop_column("site_relationships", "source_method", schema="atlas")
    op.drop_column("site_relationships", "confidence_score", schema="atlas")
    op.drop_column("site_relationships", "travel_time_minutes", schema="atlas")
    op.drop_column("site_relationships", "relationship_direction", schema="atlas")
    op.drop_column("site_relationships", "target_staging_feature_id", schema="atlas")
    # ### end Alembic commands ###
