"use client";
import { useState } from "react";
import { DataTable, DescriptionList, ImageGallery, MetricBar, StatCard, StatusBadge } from "@/components/data-display";
import { Alert, EmptyState, ErrorState, LoadingSpinner, Skeleton } from "@/components/feedback";
import { Checkbox, SearchInput, Select, TextArea, TextInput } from "@/components/forms";
import { SectionHeader } from "@/components/layout";
import { LayerTree, MapLegend, MapToolbar } from "@/components/maps";
import { Badge, Button, Card, Dialog, Divider, Drawer, IconButton, Tabs } from "@/components/ui";

export function DesignSystemShowcase() {
  const [dialog, setDialog] = useState(false); const [drawer, setDrawer] = useState(false); const [layer, setLayer] = useState(true);
  return <div className="dsShowcase">
    <Card><SectionHeader eyebrow="الإجراءات" title="الأزرار والشارات" /><div className="dsShowcaseRow"><Button>إجراء أساسي</Button><Button variant="secondary">إجراء ثانوي</Button><Button variant="ghost">إجراء هادئ</Button><Button variant="danger">إجراء حساس</Button><Button disabled>معطل</Button><Button loading>جارٍ التنفيذ</Button><IconButton label="إعدادات">⚙</IconButton><Badge tone="success">معتمد</Badge><StatusBadge status="under_review" /></div></Card>
    <Card><SectionHeader eyebrow="التنقل" title="التبويبات والحوارات" /><div className="dsShowcaseRow"><Tabs items={[{ id: "one", label: "المواقع", content: "محتوى المواقع" }, { id: "two", label: "الجودة", content: "محتوى الجودة" }]} /><Button onClick={() => setDialog(true)}>فتح Dialog</Button><Button variant="secondary" onClick={() => setDrawer(true)}>فتح Drawer</Button></div></Card>
    <Card><SectionHeader eyebrow="النماذج" title="حقول الإدخال" /><div className="dsShowcaseGrid"><SearchInput placeholder="ابحث في الأطلس" /><TextInput label="اسم الموقع" placeholder="الاسم بالعربية" /><Select label="حالة التحقق" options={[{ value: "review", label: "قيد المراجعة" }, { value: "verified", label: "معتمد" }]} /><TextInput label="حقل معطل" disabled value="غير متاح" readOnly /><TextInput label="حقل بخطأ" error="هذا الحقل مطلوب" /><TextArea label="ملاحظات المراجع" placeholder="أضف ملاحظاتك" /><Checkbox label="اعتماد المراجعة" description="يتطلب صلاحية مؤسسية" /></div></Card>
    <Card><SectionHeader eyebrow="التغذية الراجعة" title="الحالات النظامية" /><div className="dsShowcaseGrid"><Alert tone="info" title="معلومة">بيانات داخلية للاستخدام الحكومي.</Alert><Alert tone="warning" title="تنبيه">هذه البيانات قيد المراجعة.</Alert><Alert tone="danger" title="خطأ">تعذر تحميل المصدر.</Alert><EmptyState description="لم تُضف عناصر بعد." /><ErrorState description="تحقق من الاتصال ثم أعد المحاولة." /><div><LoadingSpinner /><Skeleton height={18} /><br /><Skeleton width="70%" height={18} /></div></div></Card>
    <Card><SectionHeader eyebrow="البيانات" title="البطاقات والجداول والصور" /><div className="dsShowcaseGrid"><StatCard label="إجمالي المواقع" value="8,215" note="رصيد الأطلس" /><StatCard label="قيد المراجعة" value="412" status="warning" /><ImageGallery alt="صورة نموذجية" images={["https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e?auto=format&fit=crop&w=500&q=70"]} /></div><Divider label="المقاييس" /><MetricBar label="اكتمال البيانات" value={94.7} max={100} displayValue="94.7%" /><DescriptionList items={[{ label: "المصدر", value: "LSTA" }, { label: "الحالة", value: "قيد المراجعة" }]} /><DataTable caption="عينة المواقع" rows={[{ id: "1", name: "متحف السرايا الحمراء", status: "قيد المراجعة" }]} rowKey={(row) => row.id} columns={[{ key: "name", header: "الموقع", render: (row) => row.name }, { key: "status", header: "الحالة", render: (row) => row.status }]} /></Card>
    <Card><SectionHeader eyebrow="الخرائط" title="الطبقات ومفتاح الخريطة" /><div className="dsShowcaseGrid"><LayerTree groups={[{ id: "review", label: "البيانات قيد المراجعة", items: [{ id: "old-tripoli", label: "المدينة القديمة طرابلس", color: "#7c4d9e", enabled: layer }] }]} onToggle={() => setLayer((value) => !value)} /><MapLegend items={[{ id: "p", label: "موقع سياحي", color: "#7c4d9e" }, { id: "l", label: "مسار", color: "#cf6b32", symbol: "line" }, { id: "g", label: "منطقة", color: "#d7a83c", symbol: "polygon" }]} /><div style={{ position: "relative", minHeight: 180 }}><MapToolbar onReset={() => undefined} /></div></div></Card>
    <Dialog open={dialog} title="تأكيد الإجراء" onClose={() => setDialog(false)}><p>نموذج حوار حكومي قابل لإعادة الاستخدام.</p><Button onClick={() => setDialog(false)}>موافق</Button></Dialog>
    <Drawer open={drawer} title="تفاصيل الموقع" onClose={() => setDrawer(false)}><p>لوحة جانبية لعرض تفاصيل عناصر الأطلس.</p><StatusBadge status="under_review" /></Drawer>
  </div>;
}
