export interface RegistrySummary { total_sites: number; approved: number; internal: number; archived: number; average_completeness: number }
export interface RegistrySite { id: string; national_id: string; slug: string | null; name_ar: string; name_en: string | null; verification_status: string; publication_status: string; profile_completeness_score: number }
export interface RegistryPage { items: RegistrySite[]; total: number; limit: number; offset: number }
export interface Completeness { score: number; breakdown: Record<string, { earned: number; weight: number; passed: boolean }> }
export interface SiteProfile { id?: string; short_description_ar: string | null; short_description_en: string | null; historical_period: string | null; tourism_significance: string | null; visitor_information: Record<string, unknown>; accessibility_information: Record<string, unknown>; opening_hours: Record<string, unknown>; contact_information: Record<string, unknown>; official_website: string | null; public_notes: string | null; internal_notes?: string | null }
export interface RegistryDetails extends RegistrySite { description: string | null; category_id: string | null; municipality_id: string | null; geometry: GeoJSON.Geometry | null; profile: SiteProfile; completeness: Completeness; audit_timeline: Array<{ id: string; action: string; details: Record<string, unknown>; created_at: string }> }
export interface SiteAttribute { id: string; attribute_group: string; attribute_key: string; label_ar: string; value_text: string | null; verification_status: string; is_public: boolean }
export interface SiteDocument { id: string; document_type: string; title_ar: string; file_name: string; publication_status: string; verification_status: string }
export interface SiteRelationship { relationship_id: string; relationship_type: string; source_method: string; verification_status: string; target_type: "registry" | "staging"; target_id: string; target_name: string | null; geometry_type: string | null; distance_meters: number | null; confidence_score: number | null; created_at: string; verified_at: string | null }
export interface NearbyResult { target_type: "registry" | "staging"; target_id: string; national_id?: string; feature_id?: string; name: string | null; geometry_type: string; distance_meters: number; review_status: string; quality_issues: unknown[]; longitude: number; latitude: number }
export interface NearbyResponse { center_site: { national_id: string; name: string }; radius_meters: number; total_results: number; results: NearbyResult[]; query_time_ms: number }
export interface SiteVersion { version_number: number; change_summary: string; created_at: string }
export interface RegistryFilters { search?: string; category?: string; municipality?: string; verification_status?: string; publication_status?: string; completeness_min?: number; completeness_max?: number; limit?: number; offset?: number }
